apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api2-deploy
      labels:
        app: api2
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: api2
      template:
        metadata:
          labels:
            app: api2
        spec:
          containers:
            - name: api2
              image: api2-image
              imagePullPolicy: Never
              ports:
                - containerPort: 8080
              env:
                - name: ASPNETCORE_URLS
                  value: "http://+:8080"
                - name: ASPNETCORE_ENVIRONMENT
                  value: "Development"
  - apiVersion: v1
    kind: Service
    metadata:
      name: api2-svc
    spec:
      type: NodePort
      selector:
        app: api2
      ports:
        - name: api2-port
          protocol: TCP
          port: 8080
          targetPort: 8080