apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api1-deploy
      labels:
        app: api1
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: api1
      template:
        metadata:
          labels:
            app: api1
        spec:
          containers:
            - name: api1
              image: api1-image
              imagePullPolicy: Never
              ports:
                - containerPort: 8080
  - apiVersion: v1
    kind: Service
    metadata:
      name: api1-svc
    spec:
      type: NodePort
      selector:
        app: api1
      ports:
        - name: api1-port
          protocol: TCP
          port: 8080
          targetPort: 8080